# General settings
parallel-jobs = 1
patches-version = "latest"

# ======================================================================
# YouTube
# ======================================================================
[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-inotia00]
enabled = true
app-name = "YouTube-inotia00"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "inotia00/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-anddea]
enabled = true
app-name = "YouTube-anddea"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# ======================================================================
# YouTube Music
# ======================================================================

[Music]
enabled = true
app-name = "Music"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Music-inotia00]
enabled = true
app-name = "Music-inotia00"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
patches-source = "inotia00/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Music-anddea]
enabled = true
app-name = "Music-anddea"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

# ======================================================================
# Reddit
# ======================================================================

[Reddit]
enabled = true
app-name = "Reddit"
build-mode = "apk"
version = "auto"
apkmirror-dpi = "120-640dpi"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Reddit-inotia00]
enabled = true
app-name = "Reddit-inotia00"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dpi = "120-640dpi"
patches-source = "inotia00/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Reddit-anddea]
enabled = true
app-name = "Reddit-anddea"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"


# ======================================================================
# Spotify
# ======================================================================

[Spotify]
enabled = true
app-name = "Spotify"
build-mode = "apk"
# arch = "arm64-v8a"
# apkmirror-dpi = "480dpi"
version = "9.0.54.74"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Spotify-anddea]
enabled = true
app-name = "Spotify-anddea"
build-mode = "apk"
# arch = "arm64-v8a"
# apkmirror-dpi = "480dpi"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"


# ======================================================================
# Backdrops - Wallpapers
# ======================================================================

[Backdrops]
enabled = true
version = "5.1.8"
arch = "all"
apkmirror-dpi = "120-640dpi"
build-mode = "apk"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers"

# ======================================================================
# Google News
# ======================================================================

[Google-News]
enabled = true
app-name = "google-news"
version = "auto"
build-mode = "apk"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"